### ISSUE TITLE
Teleporting in 1.10.1?

### ISSUE THREAD

**Issue by cemerson** [ImAxel0/Elden-Menu#1]
Hey there - anyone know if teleporting is working (or how to get it working) in 1.10.1? When I try any destination I am ported to high in the air and then I eventually fall/die. By the way I did try the Unstuck button but all times I fall/die.

![image](https://github.com/ImAxel0/Elden-Menu/assets/1080397/31aa5bc5-dd45-454e-bf6b-228a342b6358)

Apologies if this issue/fix has been confirmed already elsewhere. Thank you.

**Comment by ImAxel0** [comment]
Hi, I don't have the game anymore (and also time) to test or work on this but it was working fine on 1.10, so I would assume it's still working on a minor patch like 1.10.1
