### ISSUE TITLE
About Boss‘s address

### ISSUE THREAD

**Issue by a361570441** [ImAxel0/Elden-Menu#2]
Hello, I am very interested in your project, especially the part about event_flag, but I don't quite understand how the boss's ID in event_flag matches the value of event_flag? (For example, Deathbird_LimgraveAddr corresponds to { 0x28, 0xA0E1F . How did you find this matching relationship like from Deathbird_LimgraveAddr to 0xA0E1F? I would be grateful if you would disclose it.
I tried unpacking the game file but found nothing about the address except the boss's id.

**Comment by ImAxel0** [comment]
Hi, the mod is basically a port of https://www.nexusmods.com/eldenring/mods/48 from which I got the memory addresses of things (I think it was written in Lua).
0xA0E1F is just an offset to get the boss live state.
